# Assignment 7

## Submit as an HTML file

<font size = "5">
Print your name below

In [ ]:
#Ahshar Brown

<font size = "5">

Import the "pandas" and "numpy" library

In [10]:
# Write your answer here:
import pandas as pd 
import numpy as np

<font size = "5">

(a) Replace values from intervals

<font size = "3">

- Import the dataset "data_raw/students.csv" to a new object "students"
- Use "pd.cut()" to assign the column "numericgrade" to a letter grade <br>

- Using the following grading scale: <br>

<img src="figures/grading_scale.png" alt="drawing" width="600"/>

In [11]:
students = pd.read_csv('data_raw/students.csv')
numeric_grade = [0,54,59,64,69,74,79,82,86,92,93]
letter_grade = ["F","D", "C-", "C", "C+", "B-","B", "B+", "A-", "A"]

students["letter_grade"] = pd.cut(students["numericgrade"],
                                  bins=numeric_grade,
                                  right=True,
                                  labels=letter_grade)

print(students[["numericgrade", "letter_grade"]])

    numericgrade letter_grade
0             61           C-
1              0          NaN
2             14            F
3             57            D
4             72           C+
5             93            A
6             40            F
7             11            F
8              3            F
9             63           C-
10             7            F
11            46            F
12            75           B-
13            95          NaN
14            22            F
15            40            F
16            53            F
17            57            D
18            82            B
19            50            F
20             8            F
21            87           A-
22            82            B
23            30            F
24            62           C-

<font size = "5">

For questions (b)-(e) use "results.csv", <br>
a dataset on competitive car racing

Import the dataset "data_raw/results.csv" to <br>
 a new object "results"

In [12]:
# Write your own code
results = pd.read_csv("data_raw/results.csv")

<font size = "5">

(b) Check column types

<font size = "3">

- View the dataset
- Use the function "results.dtypes" to get the column types
- Search for the "results" table in "codebook/f1_codebook.pdf".
- Does the type of the "time" column agree with the codebook? <br>
i.e. is it an integer, float, or string/object?


HINT: See Lectures 12 and 14 for how to interpret the codebook

In [13]:
# Write your own code here
# Note: When you run "results.dtypes" you will get the type (int, float, object)
# Object represents columns coded as strings.
display(results)
results.dtypes

,resultId,raceId,driverId,constructorId,number,grid,position,positionText,positionOrder,points,laps,time,milliseconds,fastestLap,rank,fastestLapTime,fastestLapSpeed,statusId
0,1,18,1,1,22,1,1,1,1,10.0,58,1:34:50.616,5690616,39,2,1:27.452,218.300,1
1,2,18,2,2,3,5,2,2,2,8.0,58,+5.478,5696094,41,3,1:27.739,217.586,1
2,3,18,3,3,7,7,3,3,3,6.0,58,+8.163,5698779,41,5,1:28.090,216.719,1
3,4,18,4,4,5,11,4,4,4,5.0,58,+17.181,5707797,58,7,1:28.603,215.464,1
4,5,18,5,1,23,3,5,5,5,4.0,58,+18.014,5708630,43,1,1:27.418,218.385,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25835,25841,1096,854,210,47,12,16,16,16,0.0,57,\N,\N,39,12,1:29.833,211.632,11
25836,25842,1096,825,210,20,16,17,17,17,0.0,57,\N,\N,40,20,1:31.158,208.556,11
25837,25843,1096,1,131,44,5,18,18,18,0.0,55,\N,\N,42,11,1:29.788,211.738,9
25838,25844,1096,849,3,6,20,19,19,19,0.0,55,\N,\N,45,14,1:30.309,210.517,130
25839,25845,1096,4,214,14,10,\N,R,20,0.0,27,\N,\N,24,17,1:30.579,209.889,47

resultId             int64
raceId               int64
driverId             int64
constructorId        int64
number              object
grid                 int64
position            object
positionText        object
positionOrder        int64
points             float64
laps                 int64
time                object
milliseconds        object
fastestLap          object
rank                object
fastestLapTime      object
fastestLapSpeed     object
statusId             int64
dtype: object

<font size = "5">

(c) Clean a column

<font size = "3">

- Import the dataset "data_raw/results.csv" to a new object "results"
- Our goal is to replace any string values in the column "milliseconds" <br>
to missing values (NaNs) and covert to numeric
- To do so
    - "Extract list of non-numeric values"
    - "Replace certain values"
    - "Convert column to numeric"
    - "Display"

In [26]:
# Write your own code here
results = pd.read_csv("data_raw/results.csv")

#extracting list of non numeric values 
subset = results.query("milliseconds.str.isnumeric() == False")
list_unique = pd.unique(subset["milliseconds"])
print(list_unique)

#replace certain values 
list_old = ['\\N','-7']
list_new = [np.nan, -7]

results["milliseconds"] = results["milliseconds"].replace(list_old, list_new)
results.dtypes

#convert column to numeric 
results["milliseconds_numeric"] = pd.to_numeric(results["milliseconds"])
print(results["milliseconds_numeric"].mean())

['\\N']
6231870.430788768

<font size = "5">

(d) Groupby + Aggregate

<font size = "3">

- Compute the mean and standard deviation of "laps", <br>
grouping by "constructorId". Store the new dataset <br>
as "df_aggCon_pos"
- Sort the aggregate dataset in decending <br>
order of mean laps using ".sort_values()"

In [27]:
# Write your own code
#computing mean and std 
df_aggCon_pos = (results.groupby("constructorId")
                 .agg(mean_laps=('laps', 'mean'),
                      sd_laps=('laps', 'std'),
                      min_laps=('laps', 'min'),
                      max_laps=('laps', 'max'),
                      count_obs=('laps', 'count')))

# sort in descending
df_aggCon_pos = df_aggCon_pos.sort_values(by='mean_laps', ascending=False)
print(df_aggCon_pos)

                mean_laps    sd_laps  min_laps  max_laps  count_obs
constructorId
149            198.500000   2.121320       197       200          2
112            197.000000   4.242641       194       200          2
109            184.285714  32.912583       112       200          7
119            178.666667  36.950417       136       200          3
108            163.764706  63.148168         1       200         17
...                   ...        ...       ...       ...        ...
93               0.000000        NaN         0         0          1
61               0.000000   0.000000         0         0          2
137              0.000000        NaN         0         0          1
91               0.000000        NaN         0         0          1
74               0.000000   0.000000         0         0          8

[210 rows x 5 columns]

<font size = "5" >

(e) Query + Groupby + Aggregate

<font size = "3">

- Use ".query()" to subset observations with <br>
'race_id >= 150'
- Compute the mean and standard deviation of "position", <br>
grouping by "constructorId". Store the new dataset <br>
as "df_subAggCon_pos"

In [28]:
# Write your own code
df_subAggCon_pos = (results.query("raceId >= 150")
                    .groupby("constructorId")  # Removed raceId from grouping
                    .agg(
                        mean_position=('position', 'mean'),
                        sd_position=('position', 'std'),
                        min_position=('position', 'min'),
                        max_position=('position', 'max'),
                        count_obs=('position', 'count')))
print(df_subAggCon_pos)

TypeError: agg function failed [how->mean,dtype->object]